DATA_FORMAT_FAILURE = 'DATA_FORMAT_FAILURE'
SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
DUPLICATE = 'DUPLICATE'
VALIDATION_ERROR = 'VALIDATION_ERROR'
NOT_FOUND = 'NOT_FOUND'
TPIN_NOT_MATCH = "TPIN_NOT_MATCH"

ERROR_CODES = {
    DATA_FORMAT_FAILURE: 1001,
    SERVICE_UNAVAILABLE: 1000,
    DUPLICATE: 1002,
    VALIDATION_ERROR: 1003,
    NOT_FOUND: 1404,
    TPIN_NOT_MATCH: 1005
}