"""
Django settings for fms project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
import re
from pathlib import Path
from corsheaders.defaults import default_headers
from fms import my_keys as fms_keys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SETTINGS_DIR_VAR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if 'FMS_SECRET_KEY' in os.environ.keys():
    SECRET_KEY = os.environ['FMS_SECRET_KEY']
else:
    SECRET_KEY = fms_keys.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
if 'FMS_DEBUG' in os.environ.keys():
    DEBUG = os.environ['FMS_DEBUG'] == 'True'
else:
    DEBUG = fms_keys.DEBUG

if 'FMS_ALLOWED_HOSTS' in os.environ.keys():
    ALLOWED_HOSTS = os.environ['FMS_ALLOWED_HOSTS'].split('|')
else:
    ALLOWED_HOSTS = fms_keys.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'core',
    "corsheaders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.FirebaseTokenAuth',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'core.api_utils.custom_exception_handler',
    'DATE_INPUT_FORMATS': [
        '%d-%m-%Y',
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',
        # Any other renders
    ),
    'DEFAULT_PARSER_CLASSES': (
        # If you use MultiPartFormParser or FormParser, we also have a camel case version
        'djangorestframework_camel_case.parser.CamelCaseFormParser',
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
        # Any other parsers
    ),
    'JSON_UNDERSCOREIZE': {
        'no_underscore_before_number': True,
    },
}

IGNORABLE_404_URLS = [
    re.compile(r'\.(php|cgi|js|css|ico|png|txt)$'),
]

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

if 'FMS_EMAIL_HOST' in os.environ.keys():
    EMAIL_HOST = os.environ['FMS_EMAIL_HOST']
else:
    EMAIL_HOST = fms_keys.EMAIL_HOST

EMAIL_HOST_USER = 'apikey'
if 'FMS_EMAIL_HOST_PASSWORD' in os.environ.keys():
    EMAIL_HOST_PASSWORD = os.environ['FMS_EMAIL_HOST_PASSWORD']
else:
    EMAIL_HOST_PASSWORD = fms_keys.EMAIL_HOST_PASSWORD

EMAIL_PORT = 587
EMAIL_USE_TLS = True

CORS_ALLOW_ALL_ORIGINS = True

AWS_LOCATION = 'public/static'
AWS_DEFAULT_ACL = 'public-read'
AWS_IS_GZIPPED = True
AWS_S3_REGION_NAME = 'ap-south-1'
AWS_STORAGE_BUCKET_NAME = 'fms-cdn-dev.yashkulshreshtha.me'
# AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_CUSTOM_DOMAIN = 'fms-cdn2.dev.yashkulshreshtha.me'

if 'FMS_AWS_ACCESS_KEY_ID' in os.environ.keys():
    AWS_ACCESS_KEY_ID = os.environ['FMS_AWS_ACCESS_KEY_ID']
else:
    AWS_ACCESS_KEY_ID = fms_keys.AWS_ACCESS_KEY_ID

if 'FMS_AWS_SECRET_ACCESS_KEY' in os.environ.keys():
    AWS_SECRET_ACCESS_KEY = os.environ['FMS_AWS_SECRET_ACCESS_KEY']
else:
    AWS_SECRET_ACCESS_KEY = fms_keys.AWS_SECRET_ACCESS_KEY

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_DEFAULT_REGION = 'ap-south-1'

STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'fms.storage_backends.MediaStorage'

if 'FMS_ENABLE_SSL' in os.environ.keys():
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "Access-Control-Expose-Headers",
    "Access-Control-Allow-Headers"
]
